In [6]:
import numpy as np

#Step 1: Build the personal matrix from Student ID
student_id = "0432320005101132"

d1 = int(student_id[-1])   # last digit -> 2
d2 = int(student_id[-2])   # second last digit -> 3

A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
], dtype=float)

print("Matrix A:\n", A)

#Step 2: Analyze Matrix A
print("\nAnalysis of Matrix A ")
print("Shape of A       :", A.shape)
print("Determinant of A :", np.linalg.det(A))
print("Rank of A        :", np.linalg.matrix_rank(A))
print("Eigenvalues of A :", np.linalg.eigvals(A))

if np.linalg.det(A) != 0:
    print("Inverse of A:\n", np.linalg.inv(A))

#Step 3: Value Change Experiment
# Change top-left element by +1
B = A.copy()
B[0, 0] += 1

print("\nMatrix B:\n", B)

#Step 4: Re-analyze Matrix B
print("\nAnalysis of Matrix B ")
print("Shape of B       :", B.shape)
print("Determinant of B :", np.linalg.det(B))
print("Rank of B        :", np.linalg.matrix_rank(B))
print("Eigenvalues of B :", np.linalg.eigvals(B))

if np.linalg.det(B) != 0:
    print("Inverse of B:\n", np.linalg.inv(B))

Matrix A:
 [[4. 4.]
 [4. 5.]]

Analysis of Matrix A 
Shape of A       : (2, 2)
Determinant of A : 4.0
Rank of A        : 2
Eigenvalues of A : [0.46887113 8.53112887]
Inverse of A:
 [[ 1.25 -1.  ]
 [-1.    1.  ]]

Matrix B:
 [[5. 4.]
 [4. 5.]]

Analysis of Matrix B 
Shape of B       : (2, 2)
Determinant of B : 8.999999999999998
Rank of B        : 2
Eigenvalues of B : [9. 1.]
Inverse of B:
 [[ 0.55555556 -0.44444444]
 [-0.44444444  0.55555556]]
